language: cpp

install:
  - git clone git://sigrok.org/libserialport
  - cd libserialport
  - ./autogen.sh && ./configure --prefix=/usr && make && sudo make install
  - cd ..

before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install -qq gcc-arm-none-eabi python-yaml cmake dosfstools mtools pkg-config libusb-dev libwxgtk3.0-dev libudev-dev
  - sudo apt-get install -qq libstdc++-4.8-dev
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8" CC="gcc-4.8"

script:
  - "make"
  - "cd stm32f103/"
  - "make"
  - "cd .."
  - "cd term/"
  - "mkdir build/"
  - "cd build/"
  - "cmake ../"
  - "make"

branches:
  only:
    - master
    - motsim
  
notifications:
  irc:
    channels:
      - "irc.hackint.org#stmbl"
